server:
  port: 9093

spring:
  cloud:
    consul:
      config:
        fail-fast:true
      host: localhost # Where my consul server is running .
      port: 8500
  application:
    name: MICROSERVICE-C





eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost